### ISSUE TITLE
Not working with Jekyll 4.0.0

### ISSUE THREAD

**Issue by pavelkomarov** [benbalter/jekyll-remote-theme#66]
I've added `jekyll-remote-theme` as a `plugin` in my site's `_config.yml`. I've set `remote_theme: pavelkomarov/hyde`. If I push up to github pages, it works fine. If I `jekyll serve --verbose --trace` locally, the theme downloads, unzips, and then fails with this error message about a missing method.

```
undefined method `configure_sass'; for #<Jekyll::RemoteTheme::Theme:0x...> NoMethodError
```

There is another thread about this (#60), and you answered it was a work in progress, and then it looks from the discussion like it was solved. But I'm on `jekyll-remote-theme-0.4.1`, and it's not solved. Is this actually a Jekyll issue? Whatever the case it's making development with a remote theme really inconvenient. I don't want to have to completely deploy to see what my changes look like.

**Comment by pavelkomarov** [comment]
I managed to follow the breadcrumbs to https://github.com/jekyll/minima/issues/422#issuecomment-567089139, and then [find further evidence github-pages isn't get on Jekyll 4.0](https://stackoverflow.com/questions/58598084/how-does-one-downgrade-jekyll-to-work-with-github-pages), and then discover I have both Jekyll 3.8.5 and 4.0.0 on my machine, and then update the symlink so `which jekyll` points me at the older one, and now I'm not getting this error anymore.

I can develop locally again! Caching of the remote theme so I didn't have to download it anew each time if no updates (quickly calculable by whether a hash matches) would be handy (#22), but it's still better than having to deploy constantly.

Why does 4.0.0 break you?

**Comment by pavelkomarov** [comment]
Just discovered that following the instructions to `script/bootstrap` and `script/cibuild` also breaks five of the tests for me, because I don't have `JEKYLL_VERSION` set in my environment, so `bundler` just goes and grabs 4.0.0. If I purposefully regress jekyll to 3.8.5 by manually editing the Gemfile, then the tests all pass.

Why does 4.0.0 break you?

**Comment by hszhakka** [comment]
This problem can be solved by following these steps: https://github.com/benbalter/jekyll-remote-theme/issues/60#issuecomment-575974352.

**Comment by pavelkomarov** [comment]
Awesome. Hope that gets released to rubygems soon.
